### ISSUE TITLE
Exception in _send

### ISSUE THREAD

**Issue by brmzkw** [guyingbo/aiofluent#1]
Currently, exceptions are caught and logged in [`_send()`](https://github.com/guyingbo/aiofluent/blob/master/aiofluent/__init__.py#L102) making it impossible for applications to do something in case of exception.

Don't you think it would be better to `raise` the exception instead, and let the application choose what to do with it?

**Comment by guyingbo** [comment]
I think most people who use it don't want to handle network exceptions because usually there's nothing more they can do. If you really want to do something with the exception, you can get a "False" returned from the emit(...) call and then use last_error to get the exception object.

**Comment by guyingbo** [comment]
@brmzkw 
update: An error_callback parameter has been added for better error handling, one can ignore network exceptions by assigning error_callback=None or provide self-defined funtion to deal with exceptions.
